### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by mozhagn1991** [ChengBinJin/MRI-to-CT-DCNN-TensorFlow#8]
Hi there,
I just successfully trained the model, and I am trying to test the result using the code: 
python main.py --load_model=20200810-1641
However, I got this error:
@ChengBinJin 
Traceback (most recent call last):
  File "main.py", line 249, in <module>
    main()
  File "main.py", line 116, in main
    test(num_cross_vals, model_dir, test_dir, solver)
  File "main.py", line 195, in test
    mae[model_id], me[model_id], mse[model_id], pcc[model_id]  = solver.evaluate(ctImgs, preds, maskImgs, is_train=True)
ValueError: not enough values to unpack (expected 4, got 2)

Any idea why this happened and how to resolve it?
Appreciate

**Comment by ChengBinJin** [comment]
@mozhagn1991 In test mode, the is_train flag should be set by False. Please refer [here](https://github.com/ChengBinJin/MRI-to-CT-DCNN-TensorFlow/blob/07e2460066d90639b9081d53cd8143eabcec8b13/src/main.py#L196)
